### ISSUE TITLE
Migration vers Hexo.io

### ISSUE THREAD

**Issue by tpoisseau** [Starbound-Fr/Starbound-Fr.github.io#15]
L'Environnement NodeJS est bien plus simple d'accès que celui de ruby, bien plus accessible et reproductible.

https://hexo.io/

Éventuellement voir des alternatives type https://nextjs.org/ (React) et https://nuxtjs.org/ (Vue)

Et a terme proposer une App electron permettant la modification du site en "WYSIWYG" avec git embarqué et proposer des PR

**Comment by yohannlog** [comment]
Bonjour,
Votre commentaire a été pris en compte.
La migration sera fait avec le tout nouveau design du site que l'on va developper.
Yohann.

**Comment by Purexo** [comment]
Le compte @tpoisseau , c'est moi. C'est le compte que j'utilise au taf en fait j'avais oublié de me co avec le bon compte.
